### PR TITLE
Update Wallet code according to message forwarding support

### PR DESCRIPTION
**Pull request by shermike**
Message forwarding is introduced here https://github.com/NilFoundation/nil/pull/605

### CODE REVIEW

**Comment by KlonD90** [comment]
it looks like we need to provide ability to specify type of forward fee?

**Comment by shermike** [comment]
> it looks like we need to provide ability to specify type of forward fee?

We don't need to specify forward kind in wallet, because Wallet's `asyncCall` is only external method. And for external messages, forward kind actually does nothing, because gas will be debited from wallet's account in any case.

**Comment by KlonD90** [comment]
@shermike but I actually don't want to give rights to spend on forwarding at all?

**Review by KlonD90 — CHANGES_REQUESTED** [review]
should start with 0x code

**Review by KlonD90 — APPROVED** [review]

**Comment by KlonD90** [comment]
Should merge after release

**Pull request merged**
